CREATE TABLE candidate1135."DIM_STATES" (
	"STATE" CHAR(2) NOT NULL PRIMARY KEY,
	"STATENAME" VARCHAR
);

CREATE TABLE candidate1135."DIM_AIRPORTS" (
	"AIRPORTCODE" CHAR(3) NOT NULL PRIMARY KEY,
	"AIRPORTNAME" VARCHAR,
	"AIRPORTCITY" VARCHAR(50),
	"AIRPORTSTATE" VARCHAR(2) REFERENCES "DIM_STATES"("STATE")
);

CREATE TABLE candidate1135."DIM_AIRLINES" (
	"AIRLINECODE" CHAR(2) NOT NULL PRIMARY KEY,
	"AIRLINENAME" VARCHAR(50),
	"AIRLINENOTES" VARCHAR
);

CREATE TABLE candidate1135."FACT_FLIGHTS" (
	"TRANSACTIONID" VARCHAR NOT NULL PRIMARY KEY,
	"AIRLINECODE" CHAR(2) REFERENCES "DIM_AIRLINES"("AIRLINECODE"),
	"FLIGHTNUM" VARCHAR(4),
	"TAILNUM" VARCHAR(10),
	"FLIGHTDATE" DATE,
	"CANCELLED" BOOLEAN,
	"DIVERTED" BOOLEAN,
	"CRSELAPSEDTIME" INT,
	"ACTUALELAPSEDTIME" INT,
	"DISTANCE" VARCHAR(25),
	"DISTANCEGROUP" VARCHAR(50)
);

CREATE TABLE candidate1135."DIM_DEPARTURES" (
	"TRANSACTIONID" VARCHAR NOT NULL PRIMARY KEY REFERENCES "FACT_FLIGHTS"("TRANSACTIONID"),
	"AIRPORTCODE" CHAR(3) REFERENCES "DIM_AIRPORTS"("AIRPORTCODE"),
	"CRSDEPTIME" VARCHAR(4),
	"DEPTIME" VARCHAR(4),
	"DEPDELAY" INT,
	"TAXIOUT" INT,
	"WHEELSOFF" INT,
	"DEPDELAYGT15" CHAR(1)
);

CREATE TABLE candidate1135."DIM_ARRIVALS" (
	"TRANSACTIONID" VARCHAR NOT NULL PRIMARY KEY REFERENCES "FACT_FLIGHTS"("TRANSACTIONID"),
	"AIRPORTCODE" CHAR(3) REFERENCES "DIM_AIRPORTS"("AIRPORTCODE"),
	"CRSARRTIME" VARCHAR(4),
	"ARRTIME" VARCHAR(4),
	"ARRDELAY" INT,
	"WHEELSON" VARCHAR(4),
	"TAXIIN" INT,
	"NEXTDAYARR" CHAR(1)
);

DROP TABLE candidate1135."DIM_DEPARTURES";
DROP TABLE candidate1135."DIM_ARRIVALS";
DROP TABLE candidate1135."FACT_FLIGHTS";
DROP TABLE candidate1135."DIM_AIRLINES";
DROP TABLE candidate1135."DIM_AIRPORTS";
DROP TABLE candidate1135."DIM_STATES";

CREATE VIEW "VW_FLIGHTS" AS
SELECT TRANSACTIONID, 